In [6]:
import pandas as pd

# Filepath
folder_path = r"C:\Users\loris\Desktop\Flu_Prediction_Project"
file_path = f"{folder_path}/training_set_processed.csv"

# Charging the files
df = pd.read_csv(file_path, index_col=0)

In [7]:
df.head(5)

h1n1_concern  h1n1_knowledge  behavioral_antiviral_meds  \
0     -0.681849       -2.044279                  -0.226293   
1      1.518373        1.197027                  -0.226293   
2     -0.681849       -0.423626                  -0.226293   
3     -0.681849       -0.423626                  -0.226293   
4      0.418262       -0.423626                  -0.226293   

   behavioral_avoidance  behavioral_face_mask  behavioral_wash_hands  \
0             -1.634957             -0.272097              -2.177944   
1              0.611637             -0.272097               0.459149   
2              0.611637             -0.272097              -2.177944   
3              0.611637             -0.272097               0.459149   
4              0.611637             -0.272097               0.459149   

   behavioral_large_gatherings  behavioral_outside_home  \
0                     -0.74589                 1.404892   
1                     -0.74589                 1.404892   
2                     -0.74589                -0.711798   
3                      1.34068                -0.711798   
4                      1.34068                -0.711798   

   behavioral_touch_face  doctor_recc_h1n1  ...  income_poverty  \
0               0.687870         -0.580793  ...             0.0   
1               0.687870         -0.580793  ...             0.0   
2              -1.453764          2.608196  ...             1.0   
3              -1.453764         -0.580793  ...             0.0   
4               0.687870         -0.580793  ...             1.0   

   marital_status  rent_or_own  employment_status  hhs_geo_region  census_msa  \
0             0.0          0.0                0.0             0.0         0.0   
1             0.0          1.0                1.0             1.0         1.0   
2             0.0          0.0                1.0             2.0         1.0   
3             0.0          1.0                0.0             3.0         2.0   
4             1.0          0.0                1.0             2.0         1.0   

   employment_industry  employment_occupation  h1n1_vaccine  seasonal_vaccine  
0                 -1.0                   -1.0           0.0               0.0  
1                  0.0                    0.0           0.0               1.0  
2                  1.0                    1.0           0.0               0.0  
3                 -1.0                   -1.0           0.0               1.0  
4                  2.0                    2.0           0.0               0.0  

[5 rows x 37 columns]

# Logistic regression model

In [8]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Split the data (features/target)
X = df.drop(columns=['h1n1_vaccine', 'seasonal_vaccine'])
y_h1n1 = df['h1n1_vaccine']
y_seasonal = df['seasonal_vaccine']

# Split the data (train and test set)
X_train_h1n1, X_test_h1n1, y_train_h1n1, y_test_h1n1 = train_test_split(X, y_h1n1, test_size=0.2, random_state=42)
X_train_seasonal, X_test_seasonal, y_train_seasonal, y_test_seasonal = train_test_split(X, y_seasonal, test_size=0.2, random_state=42)

# Instantiate the logistic regression model
model_h1n1 = LogisticRegression(max_iter=1000)
model_seasonal = LogisticRegression(max_iter=1000)

# Train the model
model_h1n1.fit(X_train_h1n1, y_train_h1n1)
model_seasonal.fit(X_train_seasonal, y_train_seasonal)

# Predict 
y_pred_h1n1 = model_h1n1.predict(X_test_h1n1)
y_pred_seasonal = model_seasonal.predict(X_test_seasonal)

# Performance assessment
print("Performance pour H1N1 Vaccine:")
print(f"Accuracy: {accuracy_score(y_test_h1n1, y_pred_h1n1):.2f}")
print("Confusion Matrix:")
print(confusion_matrix(y_test_h1n1, y_pred_h1n1))
print("Classification Report:")
print(classification_report(y_test_h1n1, y_pred_h1n1))

print("\nPerformance pour Seasonal Vaccine:")
print(f"Accuracy: {accuracy_score(y_test_seasonal, y_pred_seasonal):.2f}")
print("Confusion Matrix:")
print(confusion_matrix(y_test_seasonal, y_pred_seasonal))
print("Classification Report:")
print(classification_report(y_test_seasonal, y_pred_seasonal))


Performance pour H1N1 Vaccine:
Accuracy: 0.83
Confusion Matrix:
[[3997  215]
 [ 684  446]]
Classification Report:
              precision    recall  f1-score   support

         0.0       0.85      0.95      0.90      4212
         1.0       0.67      0.39      0.50      1130

    accuracy                           0.83      5342
   macro avg       0.76      0.67      0.70      5342
weighted avg       0.82      0.83      0.81      5342


Performance pour Seasonal Vaccine:
Accuracy: 0.76
Confusion Matrix:
[[2303  588]
 [ 687 1764]]
Classification Report:
              precision    recall  f1-score   support

         0.0       0.77      0.80      0.78      2891
         1.0       0.75      0.72      0.73      2451

    accuracy                           0.76      5342
   macro avg       0.76      0.76      0.76      5342
weighted avg       0.76      0.76      0.76      5342



# Random Forest model

In [9]:

from sklearn.ensemble import RandomForestClassifier
import time

# The target columns are 'h1n1_vaccine' and 'seasonal_vaccine'
X = df.drop(columns=['h1n1_vaccine', 'seasonal_vaccine'])
y_h1n1 = df['h1n1_vaccine']
y_seasonal = df['seasonal_vaccine']

# Split the data into training and testing sets
X_train_h1n1, X_test_h1n1, y_train_h1n1, y_test_h1n1 = train_test_split(X, y_h1n1, test_size=0.2, random_state=42)
X_train_seasonal, X_test_seasonal, y_train_seasonal, y_test_seasonal = train_test_split(X, y_seasonal, test_size=0.2, random_state=42)

# Create the Random Forest model
model_h1n1 = RandomForestClassifier(n_estimators=100, random_state=42)
model_seasonal = RandomForestClassifier(n_estimators=100, random_state=42)

# Measure the training time for H1N1 model
start_time = time.time()
model_h1n1.fit(X_train_h1n1, y_train_h1n1)
training_time_h1n1 = time.time() - start_time

# Measure the prediction time for H1N1 model
start_time = time.time()
y_pred_h1n1 = model_h1n1.predict(X_test_h1n1)
prediction_time_h1n1 = time.time() - start_time

# Measure the training time for Seasonal model
start_time = time.time()
model_seasonal.fit(X_train_seasonal, y_train_seasonal)
training_time_seasonal = time.time() - start_time

# Measure the prediction time for Seasonal model
start_time = time.time()
y_pred_seasonal = model_seasonal.predict(X_test_seasonal)
prediction_time_seasonal = time.time() - start_time

# Evaluate the performance of the model
print("Performance for H1N1 Vaccine:")
print(f"Training Time: {training_time_h1n1:.2f} seconds")
print(f"Prediction Time: {prediction_time_h1n1:.2f} seconds")
print(f"Accuracy: {accuracy_score(y_test_h1n1, y_pred_h1n1):.2f}")
print("Confusion Matrix:")
print(confusion_matrix(y_test_h1n1, y_pred_h1n1))
print("Classification Report:")
print(classification_report(y_test_h1n1, y_pred_h1n1))

print("\nPerformance for Seasonal Vaccine:")
print(f"Training Time: {training_time_seasonal:.2f} seconds")
print(f"Prediction Time: {prediction_time_seasonal:.2f} seconds")
print(f"Accuracy: {accuracy_score(y_test_seasonal, y_pred_seasonal):.2f}")
print("Confusion Matrix:")
print(confusion_matrix(y_test_seasonal, y_pred_seasonal))
print("Classification Report:")
print(classification_report(y_test_seasonal, y_pred_seasonal))


Performance for H1N1 Vaccine:
Training Time: 5.36 seconds
Prediction Time: 0.23 seconds
Accuracy: 0.85
Confusion Matrix:
[[4061  151]
 [ 636  494]]
Classification Report:
              precision    recall  f1-score   support

         0.0       0.86      0.96      0.91      4212
         1.0       0.77      0.44      0.56      1130

    accuracy                           0.85      5342
   macro avg       0.82      0.70      0.73      5342
weighted avg       0.84      0.85      0.84      5342


Performance for Seasonal Vaccine:
Training Time: 5.70 seconds
Prediction Time: 0.27 seconds
Accuracy: 0.78
Confusion Matrix:
[[2356  535]
 [ 641 1810]]
Classification Report:
              precision    recall  f1-score   support

         0.0       0.79      0.81      0.80      2891
         1.0       0.77      0.74      0.75      2451

    accuracy                           0.78      5342
   macro avg       0.78      0.78      0.78      5342
weighted avg       0.78      0.78      0.78      5342


In [10]:
from sklearn.model_selection import GridSearchCV

# Définir les hyperparamètres à tester
param_grid = {
    'n_estimators': [100, 200, 300],
    'max_depth': [None, 10, 20, 30],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4],
    'max_features': ['auto', 'sqrt', 'log2'],
    'class_weight': [None, 'balanced', 'balanced_subsample']
}

# Créer un modèle Random Forest
rf = RandomForestClassifier(random_state=42)

# Configurer GridSearchCV
grid_search = GridSearchCV(estimator=rf, param_grid=param_grid, 
                           cv=5, n_jobs=-1, verbose=2, scoring='f1')

# Entraîner le modèle sur les données d'entraînement pour H1N1 Vaccine
grid_search.fit(X_train_h1n1, y_train_h1n1)

# Meilleurs hyperparamètres pour H1N1 Vaccine
best_params_h1n1 = grid_search.best_params_
print("Best parameters for H1N1 Vaccine:", best_params_h1n1)

# Entraîner le modèle avec les meilleurs hyperparamètres pour Seasonal Vaccine
grid_search.fit(X_train_seasonal, y_train_seasonal)

# Meilleurs hyperparamètres pour Seasonal Vaccine
best_params_seasonal = grid_search.best_params_
print("Best parameters for Seasonal Vaccine:", best_params_seasonal)


Fitting 5 folds for each of 972 candidates, totalling 4860 fits


C:\Users\loris\Documents\Anaconda\Lib\site-packages\sklearn\ensemble\_forest.py:424: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for RandomForestClassifiers and ExtraTreesClassifiers.
  warn(


Best parameters for H1N1 Vaccine: {'class_weight': 'balanced_subsample', 'max_depth': 20, 'max_features': 'auto', 'min_samples_leaf': 4, 'min_samples_split': 10, 'n_estimators': 300}
Fitting 5 folds for each of 972 candidates, totalling 4860 fits


C:\Users\loris\Documents\Anaconda\Lib\site-packages\sklearn\ensemble\_forest.py:424: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for RandomForestClassifiers and ExtraTreesClassifiers.
  warn(


Best parameters for Seasonal Vaccine: {'class_weight': 'balanced_subsample', 'max_depth': None, 'max_features': 'auto', 'min_samples_leaf': 4, 'min_samples_split': 10, 'n_estimators': 200}


In [11]:
import time
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Best hyperparameters for H1N1 Vaccine
best_params_h1n1 = {
    'class_weight': 'balanced_subsample',
    'max_depth': 20,
    'max_features': 'sqrt',  # Changed from 'auto' to 'sqrt'
    'min_samples_leaf': 4,
    'min_samples_split': 10,
    'n_estimators': 300
}

# Best hyperparameters for Seasonal Vaccine
best_params_seasonal = {
    'class_weight': 'balanced_subsample',
    'max_depth': None,
    'max_features': 'sqrt',  # Changed from 'auto' to 'sqrt'
    'min_samples_leaf': 4,
    'min_samples_split': 10,
    'n_estimators': 200
}

# Measure training time for the optimized model for H1N1 Vaccine
start_time = time.time()
rf_h1n1_optimized = RandomForestClassifier(**best_params_h1n1, random_state=42)
rf_h1n1_optimized.fit(X_train_h1n1, y_train_h1n1)
training_time_h1n1 = time.time() - start_time

# Measure prediction time for the optimized model for H1N1 Vaccine
start_time = time.time()
y_pred_h1n1_optimized = rf_h1n1_optimized.predict(X_test_h1n1)
prediction_time_h1n1 = time.time() - start_time

# Measure training time for the optimized model for Seasonal Vaccine
start_time = time.time()
rf_seasonal_optimized = RandomForestClassifier(**best_params_seasonal, random_state=42)
rf_seasonal_optimized.fit(X_train_seasonal, y_train_seasonal)
training_time_seasonal = time.time() - start_time

# Measure prediction time for the optimized model for Seasonal Vaccine
start_time = time.time()
y_pred_seasonal_optimized = rf_seasonal_optimized.predict(X_test_seasonal)
prediction_time_seasonal = time.time() - start_time

# Evaluate the performance of the optimized models
print("Optimized Performance for H1N1 Vaccine:")
print(f"Training Time: {training_time_h1n1:.2f} seconds")
print(f"Prediction Time: {prediction_time_h1n1:.2f} seconds")
print(f"Accuracy: {accuracy_score(y_test_h1n1, y_pred_h1n1_optimized):.2f}")
print("Confusion Matrix:")
print(confusion_matrix(y_test_h1n1, y_pred_h1n1_optimized))
print("Classification Report:")
print(classification_report(y_test_h1n1, y_pred_h1n1_optimized))

print("\nOptimized Performance for Seasonal Vaccine:")
print(f"Training Time: {training_time_seasonal:.2f} seconds")
print(f"Prediction Time: {prediction_time_seasonal:.2f} seconds")
print(f"Accuracy: {accuracy_score(y_test_seasonal, y_pred_seasonal_optimized):.2f}")
print("Confusion Matrix:")
print(confusion_matrix(y_test_seasonal, y_pred_seasonal_optimized))
print("Classification Report:")
print(classification_report(y_test_seasonal, y_pred_seasonal_optimized))



Optimized Performance for H1N1 Vaccine:
Training Time: 13.93 seconds
Prediction Time: 0.60 seconds
Accuracy: 0.84
Confusion Matrix:
[[3759  453]
 [ 417  713]]
Classification Report:
              precision    recall  f1-score   support

         0.0       0.90      0.89      0.90      4212
         1.0       0.61      0.63      0.62      1130

    accuracy                           0.84      5342
   macro avg       0.76      0.76      0.76      5342
weighted avg       0.84      0.84      0.84      5342


Optimized Performance for Seasonal Vaccine:
Training Time: 6.43 seconds
Prediction Time: 0.28 seconds
Accuracy: 0.79
Confusion Matrix:
[[2313  578]
 [ 567 1884]]
Classification Report:
              precision    recall  f1-score   support

         0.0       0.80      0.80      0.80      2891
         1.0       0.77      0.77      0.77      2451

    accuracy                           0.79      5342
   macro avg       0.78      0.78      0.78      5342
weighted avg       0.79      0.79

In [12]:
from sklearn.model_selection import cross_val_score, StratifiedKFold
from sklearn.ensemble import RandomForestClassifier
import numpy as np

# Supposons que X et y soient vos features et votre target
# X = df_processed.drop(columns=['h1n1_vaccine', 'seasonal_vaccine'])
# y_h1n1 = df_processed['h1n1_vaccine']
# y_seasonal = df_processed['seasonal_vaccine']

# Créer un modèle Random Forest avec les meilleurs hyperparamètres (vous pouvez ajuster ces paramètres)
model_h1n1 = RandomForestClassifier(
    n_estimators=300,
    max_depth=20,
    max_features='sqrt',
    min_samples_leaf=4,
    min_samples_split=10,
    class_weight='balanced_subsample',
    random_state=42
)

# Définir le K-Fold Cross Validation
kfold = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

# Effectuer la validation croisée pour le modèle H1N1
cv_results_h1n1 = cross_val_score(model_h1n1, X_train_h1n1, y_train_h1n1, cv=kfold, scoring='accuracy')

# Afficher les résultats
print("Cross-Validation Results for H1N1 Vaccine Model:")
print(f"Accuracy Scores per Fold: {cv_results_h1n1}")
print(f"Mean Accuracy: {np.mean(cv_results_h1n1):.4f}")
print(f"Standard Deviation: {np.std(cv_results_h1n1):.4f}")

# Répéter pour le modèle Seasonal Vaccine
model_seasonal = RandomForestClassifier(
    n_estimators=200,
    max_depth=None,
    max_features='sqrt',
    min_samples_leaf=4,
    min_samples_split=10,
    class_weight='balanced_subsample',
    random_state=42
)

# Effectuer la validation croisée pour le modèle Seasonal Vaccine
cv_results_seasonal = cross_val_score(model_seasonal, X_train_seasonal, y_train_seasonal, cv=kfold, scoring='accuracy')

# Afficher les résultats
print("\nCross-Validation Results for Seasonal Vaccine Model:")
print(f"Accuracy Scores per Fold: {cv_results_seasonal}")
print(f"Mean Accuracy: {np.mean(cv_results_seasonal):.4f}")
print(f"Standard Deviation: {np.std(cv_results_seasonal):.4f}")


Cross-Validation Results for H1N1 Vaccine Model:
Accuracy Scores per Fold: [0.83243623 0.84811608 0.83664872 0.84530775 0.84179733]
Mean Accuracy: 0.8409
Standard Deviation: 0.0057

Cross-Validation Results for Seasonal Vaccine Model:
Accuracy Scores per Fold: [0.79499181 0.77978001 0.77112099 0.77767377 0.77533349]
Mean Accuracy: 0.7798
Standard Deviation: 0.0081


In [13]:
!pip install optuna

import optuna
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score, StratifiedKFold

def objective(trial):
    # Hyperparamètres que vous souhaitez optimiser
    n_estimators = trial.suggest_int('n_estimators', 100, 500)
    max_depth = trial.suggest_int('max_depth', 10, 50)
    min_samples_split = trial.suggest_int('min_samples_split', 2, 20)
    min_samples_leaf = trial.suggest_int('min_samples_leaf', 1, 10)
    max_features = trial.suggest_categorical('max_features', ['sqrt', 'log2'])
    class_weight = trial.suggest_categorical('class_weight', ['balanced', 'balanced_subsample'])

    # Créer le modèle avec les hyperparamètres proposés
    model = RandomForestClassifier(
        n_estimators=n_estimators,
        max_depth=max_depth,
        min_samples_split=min_samples_split,
        min_samples_leaf=min_samples_leaf,
        max_features=max_features,
        class_weight=class_weight,
        random_state=42
    )

    # Validation croisée pour évaluer la performance
    kfold = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
    cv_scores = cross_val_score(model, X_train_h1n1, y_train_h1n1, cv=kfold, scoring='accuracy')

    return cv_scores.mean()

# Créer l'étude Optuna
study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=50)

# Meilleurs hyperparamètres trouvés par Optuna
print("Best Hyperparameters:", study.best_params)


[I 2024-08-22 04:06:00,127] A new study created in memory with name: no-name-3e2afb74-8227-4387-b313-c1db296f0fa7
[I 2024-08-22 04:06:40,102] Trial 0 finished with value: 0.844652468991341 and parameters: {'n_estimators': 380, 'max_depth': 33, 'min_samples_split': 14, 'min_samples_leaf': 1, 'max_features': 'log2', 'class_weight': 'balanced'}. Best is trial 0 with value: 0.844652468991341.
[I 2024-08-22 04:06:59,414] Trial 1 finished with value: 0.8307980341680319 and parameters: {'n_estimators': 169, 'max_depth': 30, 'min_samples_split': 19, 'min_samples_leaf': 5, 'max_features': 'log2', 'class_weight': 'balanced_subsample'}. Best is trial 0 with value: 0.844652468991341.
[I 2024-08-22 04:07:21,560] Trial 2 finished with value: 0.8503159372805993 and parameters: {'n_estimators': 164, 'max_depth': 37, 'min_samples_split': 6, 'min_samples_leaf': 2, 'max_features': 'sqrt', 'class_weight': 'balanced_subsample'}. Best is trial 2 with value: 0.8503159372805993.
[I 2024-08-22 04:08:01,103] Tr

Best Hyperparameters: {'n_estimators': 351, 'max_depth': 25, 'min_samples_split': 5, 'min_samples_leaf': 2, 'max_features': 'log2', 'class_weight': 'balanced'}


In [14]:
from sklearn.ensemble import RandomForestClassifier
import time
# Créer et entraîner le modèle Random Forest avec les hyperparamètres optimisés
model_h1n1_optimized = RandomForestClassifier(
    n_estimators=484,
    max_depth=39,
    min_samples_split=5,
    min_samples_leaf=2,
    max_features='sqrt',
    class_weight='balanced',
    random_state=42
)

# Mesurer le temps d'entraînement
start_time = time.time()
model_h1n1_optimized.fit(X_train_h1n1, y_train_h1n1)
training_time_h1n1 = time.time() - start_time

# Mesurer le temps de prédiction
start_time = time.time()
y_pred_h1n1_optimized = model_h1n1_optimized.predict(X_test_h1n1)
prediction_time_h1n1 = time.time() - start_time

# Évaluer la performance du modèle optimisé
print("Performance for Optimized H1N1 Vaccine Model:")
print(f"Training Time: {training_time_h1n1:.2f} seconds")
print(f"Prediction Time: {prediction_time_h1n1:.2f} seconds")
print(f"Accuracy: {accuracy_score(y_test_h1n1, y_pred_h1n1_optimized):.2f}")
print("Confusion Matrix:")
print(confusion_matrix(y_test_h1n1, y_pred_h1n1_optimized))
print("Classification Report:")
print(classification_report(y_test_h1n1, y_pred_h1n1_optimized))

# Créer et entraîner le modèle Random Forest avec les hyperparamètres optimisés pour Seasonal Vaccine
model_seasonal_optimized = RandomForestClassifier(
    n_estimators=484,
    max_depth=39,
    min_samples_split=5,
    min_samples_leaf=2,
    max_features='sqrt',
    class_weight='balanced',
    random_state=42
)

# Mesurer le temps d'entraînement
start_time = time.time()
model_seasonal_optimized.fit(X_train_seasonal, y_train_seasonal)
training_time_seasonal = time.time() - start_time

# Mesurer le temps de prédiction
start_time = time.time()
y_pred_seasonal_optimized = model_seasonal_optimized.predict(X_test_seasonal)
prediction_time_seasonal = time.time() - start_time

# Évaluer la performance du modèle optimisé
print("\nPerformance for Optimized Seasonal Vaccine Model:")
print(f"Training Time: {training_time_seasonal:.2f} seconds")
print(f"Prediction Time: {prediction_time_seasonal:.2f} seconds")
print(f"Accuracy: {accuracy_score(y_test_seasonal, y_pred_seasonal_optimized):.2f}")
print("Confusion Matrix:")
print(confusion_matrix(y_test_seasonal, y_pred_seasonal_optimized))
print("Classification Report:")
print(classification_report(y_test_seasonal, y_pred_seasonal_optimized))

Performance for Optimized H1N1 Vaccine Model:
Training Time: 14.27 seconds
Prediction Time: 0.67 seconds
Accuracy: 0.85
Confusion Matrix:
[[3932  280]
 [ 527  603]]
Classification Report:
              precision    recall  f1-score   support

         0.0       0.88      0.93      0.91      4212
         1.0       0.68      0.53      0.60      1130

    accuracy                           0.85      5342
   macro avg       0.78      0.73      0.75      5342
weighted avg       0.84      0.85      0.84      5342


Performance for Optimized Seasonal Vaccine Model:
Training Time: 15.23 seconds
Prediction Time: 0.85 seconds
Accuracy: 0.79
Confusion Matrix:
[[2333  558]
 [ 581 1870]]
Classification Report:
              precision    recall  f1-score   support

         0.0       0.80      0.81      0.80      2891
         1.0       0.77      0.76      0.77      2451

    accuracy                           0.79      5342
   macro avg       0.79      0.78      0.79      5342
weighted avg       0

In [15]:
import joblib

# Enregistrer le modèle optimisé pour H1N1 Vaccine
joblib.dump(model_h1n1_optimized, 'h1n1_vaccine_rfmodel.pkl')

# Enregistrer le modèle optimisé pour Seasonal Vaccine
joblib.dump(model_seasonal_optimized, 'seasonal_vaccine_rfmodel.pkl')


['seasonal_vaccine_rfmodel.pkl']

# Light GBM model

In [16]:
pip install imbalanced-learn

Note: you may need to restart the kernel to use updated packages.


In [17]:
from sklearn.model_selection import GridSearchCV
import lightgbm as lgb
from imblearn.combine import SMOTETomek
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Définir X et les deux cibles y_h1n1 et y_seasonal à partir de votre DataFrame d'entraînement
X = df.drop(columns=['h1n1_vaccine', 'seasonal_vaccine'])  # Toutes les colonnes sauf les cibles
y_h1n1 = df['h1n1_vaccine']  # Première cible
y_seasonal = df['seasonal_vaccine']  # Deuxième cible

# Séparer les données pour h1n1_vaccine avant l'application de SMOTETomek
X_train_h1n1, X_val_h1n1, y_train_h1n1, y_val_h1n1 = train_test_split(X, y_h1n1, test_size=0.2, random_state=42)

# Appliquer SMOTETomek pour rééquilibrer les classes
smote_tomek = SMOTETomek(random_state=42)
X_train_h1n1_resampled, y_train_h1n1_resampled = smote_tomek.fit_resample(X_train_h1n1, y_train_h1n1)

# Paramètres à optimiser pour LightGBM
param_grid = {
    'num_leaves': [31, 40, 50],
    'learning_rate': [0.05, 0.01, 0.1],
    'n_estimators': [100, 200, 500],
    'min_child_samples': [20, 30, 40],
    'subsample': [0.8, 0.9, 1.0],
    'colsample_bytree': [0.8, 0.9, 1.0]
}

# Créer le modèle LightGBM
lgbm = lgb.LGBMClassifier(objective='binary', metric='binary_logloss', random_state=42)

# Initialiser GridSearchCV
grid_search = GridSearchCV(estimator=lgbm, param_grid=param_grid, cv=3, scoring='accuracy', verbose=1, n_jobs=-1)

# Entraîner le modèle avec GridSearchCV
grid_search.fit(X_train_h1n1_resampled, y_train_h1n1_resampled)

# Meilleurs hyperparamètres trouvés
print(f"Best Hyperparameters: {grid_search.best_params_}")

# Faire des prédictions sur l'ensemble de validation avec le meilleur modèle
best_model_h1n1 = grid_search.best_estimator_
y_pred_h1n1 = best_model_h1n1.predict(X_val_h1n1)

# Évaluation des performances pour h1n1_vaccine
print("Performance for Optimized h1n1_vaccine Model:")
print("Accuracy:", accuracy_score(y_val_h1n1, y_pred_h1n1))
print("Confusion Matrix:\n", confusion_matrix(y_val_h1n1, y_pred_h1n1))
print("Classification Report:\n", classification_report(y_val_h1n1, y_pred_h1n1))

# Répéter le processus pour seasonal_vaccine

# Séparer les données pour seasonal_vaccine avant l'application de SMOTETomek
X_train_seasonal, X_val_seasonal, y_train_seasonal, y_val_seasonal = train_test_split(X, y_seasonal, test_size=0.2, random_state=42)

# Appliquer SMOTETomek pour rééquilibrer les classes
X_train_seasonal_resampled, y_train_seasonal_resampled = smote_tomek.fit_resample(X_train_seasonal, y_train_seasonal)

# GridSearchCV pour seasonal_vaccine
grid_search.fit(X_train_seasonal_resampled, y_train_seasonal_resampled)

# Meilleurs hyperparamètres trouvés
print(f"Best Hyperparameters for seasonal_vaccine: {grid_search.best_params_}")

# Faire des prédictions sur l'ensemble de validation avec le meilleur modèle
best_model_seasonal = grid_search.best_estimator_
y_pred_seasonal = best_model_seasonal.predict(X_val_seasonal)

# Évaluation des performances pour seasonal_vaccine
print("\nPerformance for Optimized seasonal_vaccine Model:")
print("Accuracy:", accuracy_score(y_val_seasonal, y_pred_seasonal))
print("Confusion Matrix:\n", confusion_matrix(y_val_seasonal, y_pred_seasonal))
print("Classification Report:\n", classification_report(y_val_seasonal, y_pred_seasonal))


Fitting 3 folds for each of 729 candidates, totalling 2187 fits
[LightGBM] [Info] Number of positive: 16793, number of negative: 16793
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.008981 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 8588
[LightGBM] [Info] Number of data points in the train set: 33586, number of used features: 35
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.500000 -> initscore=0.000000
Best Hyperparameters: {'colsample_bytree': 1.0, 'learning_rate': 0.01, 'min_child_samples': 20, 'n_estimators': 200, 'num_leaves': 50, 'subsample': 0.8}
Performance for Optimized h1n1_vaccine Model:
Accuracy: 0.8491201797079745
Confusion Matrix:
 [[3945  267]
 [ 539  591]]
Classification Report:
               precision    recall  f1-score   support

         0.0       0.88      0.94      0.91      4212
         1.0       0.69   

In [18]:

# Enregistrer le modèle optimisé pour H1N1 Vaccine
joblib.dump(best_model_h1n1, 'h1n1_vaccine_lgbmmodel.pkl')

# Enregistrer le modèle optimisé pour Seasonal Vaccine
joblib.dump(best_model_seasonal, 'seasonal_vaccine_lgbmmodel.pkl')

['seasonal_vaccine_lgbmmodel.pkl']

# Gradient Boosting model

In [19]:
from sklearn.ensemble import GradientBoostingClassifier

# Entraîner un modèle Gradient Boosting sur les données rééchantillonnées
gbm_model_h1n1 = GradientBoostingClassifier(n_estimators=200, learning_rate=0.05, max_depth=3, random_state=42)
gbm_model_h1n1.fit(X_train_h1n1_resampled, y_train_h1n1_resampled)

# Prédictions et évaluation
y_pred_gbm_h1n1 = gbm_model_h1n1.predict(X_val_h1n1)
print("Performance for GBM h1n1_vaccine Model:")
print("Accuracy:", accuracy_score(y_val_h1n1, y_pred_gbm_h1n1))
print("Confusion Matrix:\n", confusion_matrix(y_val_h1n1, y_pred_gbm_h1n1))
print("Classification Report:\n", classification_report(y_val_h1n1, y_pred_gbm_h1n1))

# Répéter pour seasonal_vaccine
gbm_model_seasonal = GradientBoostingClassifier(n_estimators=200, learning_rate=0.05, max_depth=3, random_state=42)
gbm_model_seasonal.fit(X_train_seasonal_resampled, y_train_seasonal_resampled)
y_pred_gbm_seasonal = gbm_model_seasonal.predict(X_val_seasonal)
print("\nPerformance for GBM seasonal_vaccine Model:")
print("Accuracy:", accuracy_score(y_val_seasonal, y_pred_gbm_seasonal))
print("Confusion Matrix:\n", confusion_matrix(y_val_seasonal, y_pred_gbm_seasonal))
print("Classification Report:\n", classification_report(y_val_seasonal, y_pred_gbm_seasonal))


Performance for GBM h1n1_vaccine Model:
Accuracy: 0.8498689629352303
Confusion Matrix:
 [[3954  258]
 [ 544  586]]
Classification Report:
               precision    recall  f1-score   support

         0.0       0.88      0.94      0.91      4212
         1.0       0.69      0.52      0.59      1130

    accuracy                           0.85      5342
   macro avg       0.79      0.73      0.75      5342
weighted avg       0.84      0.85      0.84      5342


Performance for GBM seasonal_vaccine Model:
Accuracy: 0.7901535005615874
Confusion Matrix:
 [[2355  536]
 [ 585 1866]]
Classification Report:
               precision    recall  f1-score   support

         0.0       0.80      0.81      0.81      2891
         1.0       0.78      0.76      0.77      2451

    accuracy                           0.79      5342
   macro avg       0.79      0.79      0.79      5342
weighted avg       0.79      0.79      0.79      5342



In [20]:

# Enregistrer le modèle optimisé pour H1N1 Vaccine
joblib.dump(gbm_model_h1n1, 'h1n1_vaccine_gbmmodel.pkl')

# Enregistrer le modèle optimisé pour Seasonal Vaccine
joblib.dump(gbm_model_seasonal, 'seasonal_vaccine_gbmmodel.pkl')

['seasonal_vaccine_gbmmodel.pkl']

# Stacking 

In [21]:
from sklearn.ensemble import StackingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Pour h1n1_vaccine
# Définir les modèles de base
estimators_h1n1 = [
    ('rf', model_h1n1_optimized),  # Random Forest optimisé
    ('lgbm', best_model_h1n1),     # LightGBM optimisé
    ('gbm', gbm_model_h1n1)        # GBM que vous venez d'entraîner
]

# Modèle de stacking pour h1n1_vaccine
stacking_model_h1n1 = StackingClassifier(estimators=estimators_h1n1, final_estimator=LogisticRegression())

# Entraîner le modèle de stacking sur les données rééchantillonnées
stacking_model_h1n1.fit(X_train_h1n1_resampled, y_train_h1n1_resampled)

# Faire des prédictions sur l'ensemble de validation pour h1n1_vaccine
y_pred_stack_h1n1 = stacking_model_h1n1.predict(X_val_h1n1)

# Évaluation des performances pour le modèle de stacking h1n1_vaccine
print("Performance for Stacking h1n1_vaccine Model:")
print("Accuracy:", accuracy_score(y_val_h1n1, y_pred_stack_h1n1))
print("Confusion Matrix:\n", confusion_matrix(y_val_h1n1, y_pred_stack_h1n1))
print("Classification Report:\n", classification_report(y_val_h1n1, y_pred_stack_h1n1))

# Pour seasonal_vaccine
# Définir les modèles de base
estimators_seasonal = [
    ('rf', model_seasonal_optimized),  # Random Forest optimisé
    ('lgbm', best_model_seasonal),     # LightGBM optimisé
    ('gbm', gbm_model_seasonal)        # GBM que vous venez d'entraîner
]

# Modèle de stacking pour seasonal_vaccine
stacking_model_seasonal = StackingClassifier(estimators=estimators_seasonal, final_estimator=LogisticRegression())

# Entraîner le modèle de stacking sur les données rééchantillonnées
stacking_model_seasonal.fit(X_train_seasonal_resampled, y_train_seasonal_resampled)

# Faire des prédictions sur l'ensemble de validation pour seasonal_vaccine
y_pred_stack_seasonal = stacking_model_seasonal.predict(X_val_seasonal)

# Évaluation des performances pour le modèle de stacking seasonal_vaccine
print("\nPerformance for Stacking seasonal_vaccine Model:")
print("Accuracy:", accuracy_score(y_val_seasonal, y_pred_stack_seasonal))
print("Confusion Matrix:\n", confusion_matrix(y_val_seasonal, y_pred_stack_seasonal))
print("Classification Report:\n", classification_report(y_val_seasonal, y_pred_stack_seasonal))


[LightGBM] [Info] Number of positive: 16793, number of negative: 16793
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.008521 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 8588
[LightGBM] [Info] Number of data points in the train set: 33586, number of used features: 35
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.500000 -> initscore=0.000000
[LightGBM] [Info] Number of positive: 13434, number of negative: 13434
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.011638 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 8589
[LightGBM] [Info] Number of data points in the train set: 26868, number of used features: 35
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.500000 -> initscore=0.000000
[LightGBM] [Info] Number of positive: 13435, number of negative: 13434
[LightGBM] [Info] Auto-choosing col-wise multi-thre

In [22]:
import joblib

# Spécifier le chemin du dossier
folder_path = r"C:\Users\loris\Desktop\Flu_Prediction_Project"

# Exporter le modèle de stacking pour h1n1_vaccine
joblib.dump(stacking_model_h1n1, f"{folder_path}\\stacking_h1n1_vaccine_model.pkl")

# Exporter le modèle de stacking pour seasonal_vaccine
joblib.dump(stacking_model_seasonal, f"{folder_path}\\stacking_seasonal_vaccine_model.pkl")


['C:\\Users\\loris\\Desktop\\Flu_Prediction_Project\\stacking_seasonal_vaccine_model.pkl']

# Stacking avancé

In [23]:
from sklearn.ensemble import StackingClassifier
from sklearn.ensemble import GradientBoostingClassifier

# Modèle de stacking avancé pour h1n1_vaccine avec un GBM comme modèle final
stacking_model_h1n1_advanced = StackingClassifier(
    estimators=estimators_h1n1, 
    final_estimator=GradientBoostingClassifier(n_estimators=200, learning_rate=0.05, max_depth=3)
)

# Entraîner le modèle de stacking avancé
stacking_model_h1n1_advanced.fit(X_train_h1n1_resampled, y_train_h1n1_resampled)

# Prédictions et évaluation
y_pred_advanced = stacking_model_h1n1_advanced.predict(X_val_h1n1)
print("Advanced Stacking Model Accuracy:", accuracy_score(y_val_h1n1, y_pred_advanced))


[LightGBM] [Info] Number of positive: 16793, number of negative: 16793
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.010074 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 8588
[LightGBM] [Info] Number of data points in the train set: 33586, number of used features: 35
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.500000 -> initscore=0.000000
[LightGBM] [Info] Number of positive: 13434, number of negative: 13434
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.007794 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 8589
[LightGBM] [Info] Number of data points in the train set: 26868, number of used features: 35
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.500000 -> initscore=0.000000
[LightGBM] [Info] Number of positive: 13435, number of negative: 13434
[LightGBM] [Info] Auto-choosing col-wise multi-thre

# Ensemble Learning avec Voting Classifier

In [24]:
from sklearn.ensemble import VotingClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Modèles existants
rf_model = model_h1n1_optimized         # Modèle Random Forest optimisé
lgbm_model = best_model_h1n1            # Modèle LightGBM optimisé
gbm_model = gbm_model_h1n1              # Modèle Gradient Boosting Machine

# Créer un Voting Classifier pour h1n1_vaccine
voting_clf_h1n1 = VotingClassifier(
    estimators=[
        ('rf', rf_model),
        ('lgbm', lgbm_model),
        ('gbm', gbm_model)
    ],
    voting='soft'  # Utilisez 'hard' pour le voting dur, ou 'soft' pour le voting par probabilité
)

# Entraîner le Voting Classifier
voting_clf_h1n1.fit(X_train_h1n1_resampled, y_train_h1n1_resampled)

# Faire des prédictions sur l'ensemble de validation pour h1n1_vaccine
y_pred_voting_h1n1 = voting_clf_h1n1.predict(X_val_h1n1)

# Évaluation des performances
print("Performance for Voting Classifier h1n1_vaccine Model:")
print("Accuracy:", accuracy_score(y_val_h1n1, y_pred_voting_h1n1))
print("Confusion Matrix:\n", confusion_matrix(y_val_h1n1, y_pred_voting_h1n1))
print("Classification Report:\n", classification_report(y_val_h1n1, y_pred_voting_h1n1))

# Répéter pour seasonal_vaccine
rf_model_seasonal = model_seasonal_optimized
lgbm_model_seasonal = best_model_seasonal
gbm_model_seasonal = gbm_model_seasonal

voting_clf_seasonal = VotingClassifier(
    estimators=[
        ('rf', rf_model_seasonal),
        ('lgbm', lgbm_model_seasonal),
        ('gbm', gbm_model_seasonal)
    ],
    voting='soft'  # Utilisez 'hard' pour le voting dur, ou 'soft' pour le voting par probabilité
)

# Entraîner le Voting Classifier pour seasonal_vaccine
voting_clf_seasonal.fit(X_train_seasonal_resampled, y_train_seasonal_resampled)

# Faire des prédictions sur l'ensemble de validation pour seasonal_vaccine
y_pred_voting_seasonal = voting_clf_seasonal.predict(X_val_seasonal)

# Évaluation des performances
print("\nPerformance for Voting Classifier seasonal_vaccine Model:")
print("Accuracy:", accuracy_score(y_val_seasonal, y_pred_voting_seasonal))
print("Confusion Matrix:\n", confusion_matrix(y_val_seasonal, y_pred_voting_seasonal))
print("Classification Report:\n", classification_report(y_val_seasonal, y_pred_voting_seasonal))


[LightGBM] [Info] Number of positive: 16793, number of negative: 16793
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.013519 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 8588
[LightGBM] [Info] Number of data points in the train set: 33586, number of used features: 35
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.500000 -> initscore=0.000000
Performance for Voting Classifier h1n1_vaccine Model:
Accuracy: 0.8491201797079745
Confusion Matrix:
 [[3975  237]
 [ 569  561]]
Classification Report:
               precision    recall  f1-score   support

         0.0       0.87      0.94      0.91      4212
         1.0       0.70      0.50      0.58      1130

    accuracy                           0.85      5342
   macro avg       0.79      0.72      0.74      5342
weighted avg       0.84      0.85      0.84      5342

[LightGBM] [Info] Number of positive: 10472, number of negative: 10472
[LightGBM]

In [47]:
import joblib

# Exporter le modèle Voting Classifier pour h1n1_vaccine
joblib.dump(voting_clf_h1n1, "h1n1_vaccine_voting.pkl")
print("Le modèle h1n1_vaccine_voting a été enregistré sous le nom 'h1n1_vaccine_voting.pkl'.")

# Exporter le modèle Voting Classifier pour seasonal_vaccine
joblib.dump(voting_clf_seasonal, "seasonal_vaccine_voting.pkl")
print("Le modèle seasonal_vaccine_voting a été enregistré sous le nom 'seasonal_vaccine_voting.pkl'.")


Le modèle h1n1_vaccine_voting a été enregistré sous le nom 'h1n1_vaccine_voting.pkl'.
Le modèle seasonal_vaccine_voting a été enregistré sous le nom 'seasonal_vaccine_voting.pkl'.


# SMOTETomek

In [25]:
from imblearn.combine import SMOTETomek
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Charger vos données et cibles
X = df.drop(columns=['h1n1_vaccine', 'seasonal_vaccine'])
y_h1n1 = df['h1n1_vaccine']
y_seasonal = df['seasonal_vaccine']

# Séparer les données en ensemble d'entraînement et de validation
X_train_h1n1, X_val_h1n1, y_train_h1n1, y_val_h1n1 = train_test_split(X, y_h1n1, test_size=0.2, random_state=42)

# Appliquer SMOTETomek pour rééquilibrer les classes
smote_tomek = SMOTETomek(random_state=42)
X_train_h1n1_resampled, y_train_h1n1_resampled = smote_tomek.fit_resample(X_train_h1n1, y_train_h1n1)

# Entraîner un modèle (par exemple Random Forest) sur les données rééquilibrées
model_h1n1 = RandomForestClassifier(random_state=42)
model_h1n1.fit(X_train_h1n1_resampled, y_train_h1n1_resampled)

# Prédictions et évaluation sur l'ensemble de validation
y_pred_h1n1 = model_h1n1.predict(X_val_h1n1)
print("Accuracy:", accuracy_score(y_val_h1n1, y_pred_h1n1))
print("Confusion Matrix:\n", confusion_matrix(y_val_h1n1, y_pred_h1n1))
print("Classification Report:\n", classification_report(y_val_h1n1, y_pred_h1n1))

# Répéter pour seasonal_vaccine
X_train_seasonal, X_val_seasonal, y_train_seasonal, y_val_seasonal = train_test_split(X, y_seasonal, test_size=0.2, random_state=42)
X_train_seasonal_resampled, y_train_seasonal_resampled = smote_tomek.fit_resample(X_train_seasonal, y_train_seasonal)
model_seasonal = RandomForestClassifier(random_state=42)
model_seasonal.fit(X_train_seasonal_resampled, y_train_seasonal_resampled)
y_pred_seasonal = model_seasonal.predict(X_val_seasonal)

# Évaluation des performances pour seasonal_vaccine
print("\nPerformance for seasonal_vaccine Model:")
print("Accuracy:", accuracy_score(y_val_seasonal, y_pred_seasonal))
print("Confusion Matrix:\n", confusion_matrix(y_val_seasonal, y_pred_seasonal))
print("Classification Report:\n", classification_report(y_val_seasonal, y_pred_seasonal))


Accuracy: 0.8489329839011606
Confusion Matrix:
 [[4009  203]
 [ 604  526]]
Classification Report:
               precision    recall  f1-score   support

         0.0       0.87      0.95      0.91      4212
         1.0       0.72      0.47      0.57      1130

    accuracy                           0.85      5342
   macro avg       0.80      0.71      0.74      5342
weighted avg       0.84      0.85      0.84      5342


Performance for seasonal_vaccine Model:
Accuracy: 0.7787345563459378
Confusion Matrix:
 [[2343  548]
 [ 634 1817]]
Classification Report:
               precision    recall  f1-score   support

         0.0       0.79      0.81      0.80      2891
         1.0       0.77      0.74      0.75      2451

    accuracy                           0.78      5342
   macro avg       0.78      0.78      0.78      5342
weighted avg       0.78      0.78      0.78      5342



In [26]:

# Spécifier le chemin du dossier
folder_path = r"C:\Users\loris\Desktop\Flu_Prediction_Project"

# Exporter le modèle pour h1n1_vaccine
joblib.dump(model_h1n1, f"{folder_path}\\smote_h1n1_vaccine_model.pkl")

# Exporter le modèle pour seasonal_vaccine
joblib.dump(model_seasonal, f"{folder_path}\\smote_seasonal_vaccine_model.pkl")

['C:\\Users\\loris\\Desktop\\Flu_Prediction_Project\\smote_seasonal_vaccine_model.pkl']

# XG Boost

In [27]:
import xgboost as xgb
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Créer et configurer un modèle XGBoost
xgb_model = xgb.XGBClassifier(
    scale_pos_weight=len(y_train_h1n1_resampled[y_train_h1n1_resampled == 0]) / len(y_train_h1n1_resampled[y_train_h1n1_resampled == 1]),
    objective='binary:logistic',
    use_label_encoder=False,
    eval_metric='logloss'
)

# Entraîner le modèle XGBoost
xgb_model.fit(X_train_h1n1_resampled, y_train_h1n1_resampled)

# Faire des prédictions
y_pred_h1n1_xgb = xgb_model.predict(X_val_h1n1)

# Évaluation des performances
print("Performance for XGBoost h1n1_vaccine Model:")
print("Accuracy:", accuracy_score(y_val_h1n1, y_pred_h1n1_xgb))
print("Confusion Matrix:\n", confusion_matrix(y_val_h1n1, y_pred_h1n1_xgb))
print("Classification Report:\n", classification_report(y_val_h1n1, y_pred_h1n1_xgb))

# Répéter pour seasonal_vaccine
xgb_model_seasonal = xgb.XGBClassifier(
    scale_pos_weight=len(y_train_seasonal_resampled[y_train_seasonal_resampled == 0]) / len(y_train_seasonal_resampled[y_train_seasonal_resampled == 1]),
    objective='binary:logistic',
    use_label_encoder=False,
    eval_metric='logloss'
)

xgb_model_seasonal.fit(X_train_seasonal_resampled, y_train_seasonal_resampled)
y_pred_seasonal_xgb = xgb_model_seasonal.predict(X_val_seasonal)

# Évaluation des performances pour seasonal_vaccine
print("\nPerformance for XGBoost seasonal_vaccine Model:")
print("Accuracy:", accuracy_score(y_val_seasonal, y_pred_seasonal_xgb))
print("Confusion Matrix:\n", confusion_matrix(y_val_seasonal, y_pred_seasonal_xgb))
print("Classification Report:\n", classification_report(y_val_seasonal, y_pred_seasonal_xgb))


Performance for XGBoost h1n1_vaccine Model:
Accuracy: 0.8515537251965556
Confusion Matrix:
 [[3947  265]
 [ 528  602]]
Classification Report:
               precision    recall  f1-score   support

         0.0       0.88      0.94      0.91      4212
         1.0       0.69      0.53      0.60      1130

    accuracy                           0.85      5342
   macro avg       0.79      0.73      0.76      5342
weighted avg       0.84      0.85      0.84      5342


Performance for XGBoost seasonal_vaccine Model:
Accuracy: 0.7811681018345189
Confusion Matrix:
 [[2319  572]
 [ 597 1854]]
Classification Report:
               precision    recall  f1-score   support

         0.0       0.80      0.80      0.80      2891
         1.0       0.76      0.76      0.76      2451

    accuracy                           0.78      5342
   macro avg       0.78      0.78      0.78      5342
weighted avg       0.78      0.78      0.78      5342



In [28]:
# Spécifier le chemin du dossier
folder_path = r"C:\Users\loris\Desktop\Flu_Prediction_Project"

# Exporter le modèle  pour h1n1_vaccine
joblib.dump(xgb_model, f"{folder_path}\\h1n1_vaccine_xgbmodel.pkl")

# Exporter le modèle pour seasonal_vaccine
joblib.dump(xgb_model_seasonal, f"{folder_path}\\seasonal_vaccine_xgbmodel.pkl")

['C:\\Users\\loris\\Desktop\\Flu_Prediction_Project\\seasonal_vaccine_xgbmodel.pkl']

# Ada boost

In [29]:
from sklearn.ensemble import AdaBoostClassifier

# Créer et configurer un modèle AdaBoost
ada_model = AdaBoostClassifier(
    n_estimators=100,  # Nombre d'estimateurs faibles
    learning_rate=0.5  # Taux d'apprentissage
)

# Entraîner le modèle AdaBoost
ada_model.fit(X_train_h1n1_resampled, y_train_h1n1_resampled)

# Faire des prédictions
y_pred_h1n1_ada = ada_model.predict(X_val_h1n1)

# Évaluation des performances
print("Performance for AdaBoost h1n1_vaccine Model:")
print("Accuracy:", accuracy_score(y_val_h1n1, y_pred_h1n1_ada))
print("Confusion Matrix:\n", confusion_matrix(y_val_h1n1, y_pred_h1n1_ada))
print("Classification Report:\n", classification_report(y_val_h1n1, y_pred_h1n1_ada))

# Répéter pour seasonal_vaccine
ada_model_seasonal = AdaBoostClassifier(
    n_estimators=100,
    learning_rate=0.5
)

ada_model_seasonal.fit(X_train_seasonal_resampled, y_train_seasonal_resampled)
y_pred_seasonal_ada = ada_model_seasonal.predict(X_val_seasonal)

# Évaluation des performances pour seasonal_vaccine
print("\nPerformance for AdaBoost seasonal_vaccine Model:")
print("Accuracy:", accuracy_score(y_val_seasonal, y_pred_seasonal_ada))
print("Confusion Matrix:\n", confusion_matrix(y_val_seasonal, y_pred_seasonal_ada))
print("Classification Report:\n", classification_report(y_val_seasonal, y_pred_seasonal_ada))


Performance for AdaBoost h1n1_vaccine Model:
Accuracy: 0.8429427180831149
Confusion Matrix:
 [[3843  369]
 [ 470  660]]
Classification Report:
               precision    recall  f1-score   support

         0.0       0.89      0.91      0.90      4212
         1.0       0.64      0.58      0.61      1130

    accuracy                           0.84      5342
   macro avg       0.77      0.75      0.76      5342
weighted avg       0.84      0.84      0.84      5342


Performance for AdaBoost seasonal_vaccine Model:
Accuracy: 0.7821040808685885
Confusion Matrix:
 [[2342  549]
 [ 615 1836]]
Classification Report:
               precision    recall  f1-score   support

         0.0       0.79      0.81      0.80      2891
         1.0       0.77      0.75      0.76      2451

    accuracy                           0.78      5342
   macro avg       0.78      0.78      0.78      5342
weighted avg       0.78      0.78      0.78      5342



In [30]:
# Spécifier le chemin du dossier
folder_path = r"C:\Users\loris\Desktop\Flu_Prediction_Project"

# Exporter le modèle  pour h1n1_vaccine
joblib.dump(ada_model, f"{folder_path}\\h1n1_vaccine_adamodel.pkl")

# Exporter le modèle pour seasonal_vaccine
joblib.dump(ada_model_seasonal, f"{folder_path}\\seasonal_vaccine_adamodel.pkl")

['C:\\Users\\loris\\Desktop\\Flu_Prediction_Project\\seasonal_vaccine_adamodel.pkl']

# Stacking avancé bis

In [31]:
from sklearn.ensemble import StackingClassifier
from sklearn.model_selection import train_test_split
from sklearn.ensemble import GradientBoostingClassifier, RandomForestClassifier, AdaBoostClassifier
import xgboost as xgb
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Charger vos données
X = df.drop(columns=['h1n1_vaccine', 'seasonal_vaccine'])
y_h1n1 = df['h1n1_vaccine']
y_seasonal = df['seasonal_vaccine']

# Séparer les données en ensemble d'entraînement et de validation
X_train_h1n1, X_val_h1n1, y_train_h1n1, y_val_h1n1 = train_test_split(X, y_h1n1, test_size=0.2, random_state=42)

# Définir les modèles de base
base_models = [
    ('rf', RandomForestClassifier(n_estimators=100, random_state=42)),
    ('xgb', xgb.XGBClassifier(scale_pos_weight=len(y_train_h1n1[y_train_h1n1 == 0]) / len(y_train_h1n1[y_train_h1n1 == 1]), random_state=42)),
    ('ada', AdaBoostClassifier(n_estimators=100, learning_rate=0.5, random_state=42)),
]

# Modèle de niveau supérieur
level_2_model = GradientBoostingClassifier(n_estimators=100, learning_rate=0.05, random_state=42)

# Créer le Stacking Classifier
stacking_model = StackingClassifier(estimators=base_models, final_estimator=level_2_model, cv=5)

# Entraîner le modèle empilé pour h1n1_vaccine
stacking_model.fit(X_train_h1n1, y_train_h1n1)

# Faire des prédictions sur l'ensemble de validation pour h1n1_vaccine
y_pred_h1n1 = stacking_model.predict(X_val_h1n1)

# Évaluation des performances pour h1n1_vaccine
print("Performance for Stacked h1n1_vaccine Model:")
print("Accuracy:", accuracy_score(y_val_h1n1, y_pred_h1n1))
print("Confusion Matrix:\n", confusion_matrix(y_val_h1n1, y_pred_h1n1))
print("Classification Report:\n", classification_report(y_val_h1n1, y_pred_h1n1))

# Répéter les mêmes étapes pour seasonal_vaccine
X_train_seasonal, X_val_seasonal, y_train_seasonal, y_val_seasonal = train_test_split(X, y_seasonal, test_size=0.2, random_state=42)

stacking_model_seasonal = StackingClassifier(estimators=base_models, final_estimator=level_2_model, cv=5)
stacking_model_seasonal.fit(X_train_seasonal, y_train_seasonal)

y_pred_seasonal = stacking_model_seasonal.predict(X_val_seasonal)

# Évaluation des performances pour seasonal_vaccine
print("\nPerformance for Stacked seasonal_vaccine Model:")
print("Accuracy:", accuracy_score(y_val_seasonal, y_pred_seasonal))
print("Confusion Matrix:\n", confusion_matrix(y_val_seasonal, y_pred_seasonal))
print("Classification Report:\n", classification_report(y_val_seasonal, y_pred_seasonal))


Performance for Stacked h1n1_vaccine Model:
Accuracy: 0.8545488581055785
Confusion Matrix:
 [[4024  188]
 [ 589  541]]
Classification Report:
               precision    recall  f1-score   support

         0.0       0.87      0.96      0.91      4212
         1.0       0.74      0.48      0.58      1130

    accuracy                           0.85      5342
   macro avg       0.81      0.72      0.75      5342
weighted avg       0.84      0.85      0.84      5342


Performance for Stacked seasonal_vaccine Model:
Accuracy: 0.7905278921752152
Confusion Matrix:
 [[2371  520]
 [ 599 1852]]
Classification Report:
               precision    recall  f1-score   support

         0.0       0.80      0.82      0.81      2891
         1.0       0.78      0.76      0.77      2451

    accuracy                           0.79      5342
   macro avg       0.79      0.79      0.79      5342
weighted avg       0.79      0.79      0.79      5342



# Neuronal network

In [32]:
!pip install tensorflow

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Charger et préparer les données
X = df.drop(columns=['h1n1_vaccine', 'seasonal_vaccine'])
y_h1n1 = df['h1n1_vaccine']
y_seasonal = df['seasonal_vaccine']


# Séparer les données en ensemble d'entraînement et de validation
X_train_h1n1, X_val_h1n1, y_train_h1n1, y_val_h1n1 = train_test_split(X, y_h1n1, test_size=0.2, random_state=42)

# Construire le modèle de réseau de neurones
model = Sequential([
    Dense(128, input_dim=X_train_h1n1.shape[1], activation='relu'),
    Dropout(0.3),
    Dense(64, activation='relu'),
    Dropout(0.3),
    Dense(32, activation='relu'),
    Dense(1, activation='sigmoid')
])

# Compiler le modèle
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Entraîner le modèle
history = model.fit(X_train_h1n1, y_train_h1n1, epochs=50, batch_size=32, validation_data=(X_val_h1n1, y_val_h1n1), verbose=1)

# Évaluer le modèle sur l'ensemble de validation
y_pred_h1n1 = model.predict(X_val_h1n1)
y_pred_h1n1_binary = (y_pred_h1n1 > 0.5).astype(int)

# Afficher les résultats
print("Performance for Neural Network h1n1_vaccine Model:")
print("Accuracy:", accuracy_score(y_val_h1n1, y_pred_h1n1_binary))
print("Confusion Matrix:\n", confusion_matrix(y_val_h1n1, y_pred_h1n1_binary))
print("Classification Report:\n", classification_report(y_val_h1n1, y_pred_h1n1_binary))

# Répéter pour seasonal_vaccine
X_train_seasonal, X_val_seasonal, y_train_seasonal, y_val_seasonal = train_test_split(X, y_seasonal, test_size=0.2, random_state=42)

model_seasonal = Sequential([
    Dense(128, input_dim=X_train_seasonal.shape[1], activation='relu'),
    Dropout(0.3),
    Dense(64, activation='relu'),
    Dropout(0.3),
    Dense(32, activation='relu'),
    Dense(1, activation='sigmoid')
])

model_seasonal.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

history_seasonal = model_seasonal.fit(X_train_seasonal, y_train_seasonal, epochs=50, batch_size=32, validation_data=(X_val_seasonal, y_val_seasonal), verbose=1)

y_pred_seasonal = model_seasonal.predict(X_val_seasonal)
y_pred_seasonal_binary = (y_pred_seasonal > 0.5).astype(int)

print("\nPerformance for Neural Network seasonal_vaccine Model:")
print("Accuracy:", accuracy_score(y_val_seasonal, y_pred_seasonal_binary))
print("Confusion Matrix:\n", confusion_matrix(y_val_seasonal, y_pred_seasonal_binary))
print("Classification Report:\n", classification_report(y_val_seasonal, y_pred_seasonal_binary))


C:\Users\loris\Documents\Anaconda\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Epoch 1/50
668/668 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.7878 - loss: 0.4876 - val_accuracy: 0.8317 - val_loss: 0.3964
Epoch 2/50
668/668 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8310 - loss: 0.3967 - val_accuracy: 0.8446 - val_loss: 0.3719
Epoch 3/50
668/668 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8401 - loss: 0.3782 - val_accuracy: 0.8476 - val_loss: 0.3646
Epoch 4/50
668/668 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8526 - loss: 0.3551 - val_accuracy: 0.8474 - val_loss: 0.3633
Epoch 5/50
668/668 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8561 - loss: 0.3503 - val_accuracy: 0.8501 - val_loss: 0.3577
Epoch 6/50
668/668 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8536 - loss: 0.3614 - val_accuracy: 0.8493 - val_loss: 0.3704
Epoch 7/50
668/668 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8506 - loss: 0.3657 - val_accuracy: 0.8504 - val_loss: 0.3533
Epoch 8/50
668/668 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8573 - loss: 0.3500 - val_accuracy: 0.

C:\Users\loris\Documents\Anaconda\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


668/668 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.6573 - loss: 0.6167 - val_accuracy: 0.7634 - val_loss: 0.5021
Epoch 2/50
668/668 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7489 - loss: 0.5245 - val_accuracy: 0.7671 - val_loss: 0.4979
Epoch 3/50
668/668 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7581 - loss: 0.5100 - val_accuracy: 0.7707 - val_loss: 0.4914
Epoch 4/50
668/668 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7653 - loss: 0.4957 - val_accuracy: 0.7701 - val_loss: 0.4923
Epoch 5/50
668/668 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7685 - loss: 0.4946 - val_accuracy: 0.7731 - val_loss: 0.4891
Epoch 6/50
668/668 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7642 - loss: 0.4972 - val_accuracy: 0.7739 - val_loss: 0.4889
Epoch 7/50
668/668 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7676 - loss: 0.4905 - val_accuracy: 0.7716 - val_loss: 0.4898
Epoch 8/50
668/668 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7703 - loss: 0.4912 - val_accuracy: 0.7742 - val_

In [33]:
# Spécifier le chemin du dossier
folder_path = r"C:\Users\loris\Desktop\Flu_Prediction_Project"

# Exporter le modèle pour h1n1_vaccine
joblib.dump(model, f"{folder_path}\\h1n1_vaccine_neuronalmodel.pkl")

# Exporter le modèle pour seasonal_vaccine
joblib.dump(model_seasonal, f"{folder_path}\\seasonal_vaccine_neuronalmodel.pkl")

['C:\\Users\\loris\\Desktop\\Flu_Prediction_Project\\seasonal_vaccine_neuronalmodel.pkl']

# Neuronal network with L2 & Dropout

In [34]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.regularizers import l2
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Charger et préparer les données
X = df.drop(columns=['h1n1_vaccine', 'seasonal_vaccine'])
y_h1n1 = df['h1n1_vaccine']
y_seasonal = df['seasonal_vaccine']

# Normaliser les données
scaler = StandardScaler()
X = scaler.fit_transform(X)

# Séparer les données en ensemble d'entraînement et de validation
X_train_h1n1, X_val_h1n1, y_train_h1n1, y_val_h1n1 = train_test_split(X, y_h1n1, test_size=0.2, random_state=42)

# Construire le modèle de réseau de neurones avec régularisation L2 et Dropout
model = Sequential([
    Dense(128, input_dim=X_train_h1n1.shape[1], activation='relu', kernel_regularizer=l2(0.01)),
    Dropout(0.4),  # Dropout de 40%
    Dense(64, activation='relu', kernel_regularizer=l2(0.01)),
    Dropout(0.4),  # Dropout de 40%
    Dense(32, activation='relu', kernel_regularizer=l2(0.01)),
    Dense(1, activation='sigmoid')
])

# Compiler le modèle
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Entraîner le modèle
history = model.fit(X_train_h1n1, y_train_h1n1, epochs=100, batch_size=32, validation_data=(X_val_h1n1, y_val_h1n1), verbose=1)

# Évaluer le modèle sur l'ensemble de validation
y_pred_h1n1 = model.predict(X_val_h1n1)
y_pred_h1n1_binary = (y_pred_h1n1 > 0.5).astype(int)

# Afficher les résultats
print("Performance for Neural Network with Regularization h1n1_vaccine Model:")
print("Accuracy:", accuracy_score(y_val_h1n1, y_pred_h1n1_binary))
print("Confusion Matrix:\n", confusion_matrix(y_val_h1n1, y_pred_h1n1_binary))
print("Classification Report:\n", classification_report(y_val_h1n1, y_pred_h1n1_binary))

# Répéter pour seasonal_vaccine
X_train_seasonal, X_val_seasonal, y_train_seasonal, y_val_seasonal = train_test_split(X, y_seasonal, test_size=0.2, random_state=42)

model_seasonal = Sequential([
    Dense(128, input_dim=X_train_seasonal.shape[1], activation='relu', kernel_regularizer=l2(0.01)),
    Dropout(0.4),
    Dense(64, activation='relu', kernel_regularizer=l2(0.01)),
    Dropout(0.4),
    Dense(32, activation='relu', kernel_regularizer=l2(0.01)),
    Dense(1, activation='sigmoid')
])

model_seasonal.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

history_seasonal = model_seasonal.fit(X_train_seasonal, y_train_seasonal, epochs=100, batch_size=32, validation_data=(X_val_seasonal, y_val_seasonal), verbose=1)

y_pred_seasonal = model_seasonal.predict(X_val_seasonal)
y_pred_seasonal_binary = (y_pred_seasonal > 0.5).astype(int)

print("\nPerformance for Neural Network with Regularization seasonal_vaccine Model:")
print("Accuracy:", accuracy_score(y_val_seasonal, y_pred_seasonal_binary))
print("Confusion Matrix:\n", confusion_matrix(y_val_seasonal, y_pred_seasonal_binary))
print("Classification Report:\n", classification_report(y_val_seasonal, y_pred_seasonal_binary))


C:\Users\loris\Documents\Anaconda\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Epoch 1/100
668/668 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.7847 - loss: 1.3369 - val_accuracy: 0.8424 - val_loss: 0.4528
Epoch 2/100
668/668 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8389 - loss: 0.4480 - val_accuracy: 0.8443 - val_loss: 0.4186
Epoch 3/100
668/668 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8417 - loss: 0.4287 - val_accuracy: 0.8428 - val_loss: 0.4263
Epoch 4/100
668/668 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8420 - loss: 0.4206 - val_accuracy: 0.8480 - val_loss: 0.4092
Epoch 5/100
668/668 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8385 - loss: 0.4225 - val_accuracy: 0.8407 - val_loss: 0.4117
Epoch 6/100
668/668 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8468 - loss: 0.4134 - val_accuracy: 0.8330 - val_loss: 0.4323
Epoch 7/100
668/668 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8490 - loss: 0.4063 - val_accuracy: 0.8437 - val_loss: 0.4050
Epoch 8/100
668/668 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8447 - loss: 0.4169 - val_accu

C:\Users\loris\Documents\Anaconda\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


668/668 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.6783 - loss: 1.4762 - val_accuracy: 0.7684 - val_loss: 0.5810
Epoch 2/100
668/668 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7529 - loss: 0.5808 - val_accuracy: 0.7585 - val_loss: 0.5533
Epoch 3/100
668/668 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7580 - loss: 0.5585 - val_accuracy: 0.7712 - val_loss: 0.5417
Epoch 4/100
668/668 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7573 - loss: 0.5518 - val_accuracy: 0.7598 - val_loss: 0.5413
Epoch 5/100
668/668 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7550 - loss: 0.5508 - val_accuracy: 0.7671 - val_loss: 0.5370
Epoch 6/100
668/668 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7617 - loss: 0.5466 - val_accuracy: 0.7701 - val_loss: 0.5304
Epoch 7/100
668/668 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7560 - loss: 0.5558 - val_accuracy: 0.7658 - val_loss: 0.5381
Epoch 8/100
668/668 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7613 - loss: 0.5479 - val_accuracy: 0.7606

# Neuronal network + ensemble + voting classifier

In [36]:
import joblib
from sklearn.ensemble import VotingClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Charger les modèles pré-entraînés
folder_path = r"C:\Users\loris\Desktop\Flu_Prediction_Project"

h1n1_vaccine_rfmodel = joblib.load(f"{folder_path}\\h1n1_vaccine_rfmodel.pkl")
seasonal_vaccine_rfmodel = joblib.load(f"{folder_path}\\seasonal_vaccine_rfmodel.pkl")
stacking_h1n1_vaccine_model = joblib.load(f"{folder_path}\\stacking_h1n1_vaccine_model.pkl")
stacking_seasonal_vaccine_model = joblib.load(f"{folder_path}\\stacking_seasonal_vaccine_model.pkl")

# Assurez-vous que X_train_h1n1, y_train_h1n1, X_val_h1n1, y_val_h1n1 soient déjà définis dans le notebook

# Créer le Voting Classifier pour h1n1_vaccine
voting_clf_h1n1 = VotingClassifier(estimators=[
    ('rf', h1n1_vaccine_rfmodel),
    ('stacking', stacking_h1n1_vaccine_model)
], voting='soft')

# Entraîner le Voting Classifier pour h1n1_vaccine
voting_clf_h1n1.fit(X_train_h1n1, y_train_h1n1)

# Faire des prédictions sur l'ensemble de validation
y_pred_h1n1 = voting_clf_h1n1.predict(X_val_h1n1)

# Évaluer les performances
print("Performance for Voting Classifier h1n1_vaccine Model:")
print("Accuracy:", accuracy_score(y_val_h1n1, y_pred_h1n1))
print("Confusion Matrix:\n", confusion_matrix(y_val_h1n1, y_pred_h1n1))
print("Classification Report:\n", classification_report(y_val_h1n1, y_pred_h1n1))

# Répéter pour seasonal_vaccine
voting_clf_seasonal = VotingClassifier(estimators=[
    ('rf', seasonal_vaccine_rfmodel),
    ('stacking', stacking_seasonal_vaccine_model)
], voting='soft')

voting_clf_seasonal.fit(X_train_seasonal, y_train_seasonal)

y_pred_seasonal = voting_clf_seasonal.predict(X_val_seasonal)

print("\nPerformance for Voting Classifier seasonal_vaccine Model:")
print("Accuracy:", accuracy_score(y_val_seasonal, y_pred_seasonal))
print("Confusion Matrix:\n", confusion_matrix(y_val_seasonal, y_pred_seasonal))
print("Classification Report:\n", classification_report(y_val_seasonal, y_pred_seasonal))


[LightGBM] [Info] Number of positive: 4544, number of negative: 16821
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.003890 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 198
[LightGBM] [Info] Number of data points in the train set: 21365, number of used features: 35
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.212684 -> initscore=-1.308820
[LightGBM] [Info] Start training from score -1.308820
[LightGBM] [Info] Number of positive: 3636, number of negative: 13456
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.003622 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 198
[LightGBM] [Info] Number of data points in the train set: 17092, number of used features: 35
[LightGBM] [Info] [bin

In [48]:
import joblib

# Exporter le modèle Voting Classifier pour h1n1_vaccine
joblib.dump(voting_clf_h1n1, f"{folder_path}\\h1n1_vaccine_neurovoting.pkl")
print("Le modèle h1n1_vaccine_neurovoting a été enregistré sous le nom 'h1n1_vaccine_neurovoting.pkl'.")

# Exporter le modèle Voting Classifier pour seasonal_vaccine
joblib.dump(voting_clf_seasonal, f"{folder_path}\\seasonal_vaccine_neurovoting.pkl")
print("Le modèle seasonal_vaccine_neurovoting a été enregistré sous le nom 'seasonal_vaccine_neurovoting.pkl'.")


Le modèle h1n1_vaccine_neurovoting a été enregistré sous le nom 'h1n1_vaccine_neurovoting.pkl'.
Le modèle seasonal_vaccine_neurovoting a été enregistré sous le nom 'seasonal_vaccine_neurovoting.pkl'.


# SMOTE + undersampling

In [38]:
from imblearn.combine import SMOTEENN 
from imblearn.under_sampling import RandomUnderSampler
from imblearn.over_sampling import SMOTE  # Importation de SMOTE
from imblearn.pipeline import Pipeline as ImbPipeline
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.model_selection import train_test_split

# Charger et préparer les données
X = df.drop(columns=['h1n1_vaccine', 'seasonal_vaccine'])
y_h1n1 = df['h1n1_vaccine']
y_seasonal = df['seasonal_vaccine']

# Séparer les données en ensemble d'entraînement et de validation
X_train_h1n1, X_val_h1n1, y_train_h1n1, y_val_h1n1 = train_test_split(X, y_h1n1, test_size=0.2, random_state=42)
X_train_seasonal, X_val_seasonal, y_train_seasonal, y_val_seasonal = train_test_split(X, y_seasonal, test_size=0.2, random_state=42)

# Créer un pipeline pour rééquilibrer les classes
smote = SMOTE(sampling_strategy='minority', random_state=42)
under = RandomUnderSampler(sampling_strategy='majority', random_state=42)

# Pipeline pour h1n1_vaccine
pipeline_h1n1 = ImbPipeline(steps=[('smote', smote), ('under', under), ('model', GradientBoostingClassifier(n_estimators=100, learning_rate=0.1, random_state=42))])

# Entraîner le modèle après rééquilibrage
pipeline_h1n1.fit(X_train_h1n1, y_train_h1n1)

# Faire des prédictions
y_pred_h1n1 = pipeline_h1n1.predict(X_val_h1n1)

# Évaluer les performances
print("Performance for Balanced Gradient Boosting h1n1_vaccine Model:")
print("Accuracy:", accuracy_score(y_val_h1n1, y_pred_h1n1))
print("Confusion Matrix:\n", confusion_matrix(y_val_h1n1, y_pred_h1n1))
print("Classification Report:\n", classification_report(y_val_h1n1, y_pred_h1n1))

# Pipeline pour seasonal_vaccine
pipeline_seasonal = ImbPipeline(steps=[('smote', smote), ('under', under), ('model', GradientBoostingClassifier(n_estimators=100, learning_rate=0.1, random_state=42))])

# Entraîner le modèle après rééquilibrage
pipeline_seasonal.fit(X_train_seasonal, y_train_seasonal)

# Faire des prédictions
y_pred_seasonal = pipeline_seasonal.predict(X_val_seasonal)

# Évaluer les performances
print("\nPerformance for Balanced Gradient Boosting seasonal_vaccine Model:")
print("Accuracy:", accuracy_score(y_val_seasonal, y_pred_seasonal))
print("Confusion Matrix:\n", confusion_matrix(y_val_seasonal, y_pred_seasonal))
print("Classification Report:\n", classification_report(y_val_seasonal, y_pred_seasonal))



Performance for Balanced Gradient Boosting h1n1_vaccine Model:
Accuracy: 0.850430550355672
Confusion Matrix:
 [[3947  265]
 [ 534  596]]
Classification Report:
               precision    recall  f1-score   support

         0.0       0.88      0.94      0.91      4212
         1.0       0.69      0.53      0.60      1130

    accuracy                           0.85      5342
   macro avg       0.79      0.73      0.75      5342
weighted avg       0.84      0.85      0.84      5342


Performance for Balanced Gradient Boosting seasonal_vaccine Model:
Accuracy: 0.7905278921752152
Confusion Matrix:
 [[2346  545]
 [ 574 1877]]
Classification Report:
               precision    recall  f1-score   support

         0.0       0.80      0.81      0.81      2891
         1.0       0.77      0.77      0.77      2451

    accuracy                           0.79      5342
   macro avg       0.79      0.79      0.79      5342
weighted avg       0.79      0.79      0.79      5342



# Optimizing the recall for the minority class (5 steps)

In [39]:
# Étape 1 : Ajustement du Seuil de Décision
y_proba_h1n1 = model_h1n1_optimized.predict_proba(X_val_h1n1)[:, 1]
threshold = 0.3
y_pred_h1n1_adjusted = [1 if prob > threshold else 0 for prob in y_proba_h1n1]
print("Confusion Matrix:\n", confusion_matrix(y_val_h1n1, y_pred_h1n1_adjusted))
print("Classification Report:\n", classification_report(y_val_h1n1, y_pred_h1n1_adjusted))


Confusion Matrix:
 [[3340  872]
 [ 246  884]]
Classification Report:
               precision    recall  f1-score   support

         0.0       0.93      0.79      0.86      4212
         1.0       0.50      0.78      0.61      1130

    accuracy                           0.79      5342
   macro avg       0.72      0.79      0.73      5342
weighted avg       0.84      0.79      0.81      5342



In [41]:
# Étape 2 : Pondération des Classes
from sklearn.experimental import enable_hist_gradient_boosting  # Nécessaire pour activer le modèle
from sklearn.ensemble import HistGradientBoostingClassifier

# Modèle avec pondération des classes
model_h1n1_weighted = HistGradientBoostingClassifier(random_state=42, class_weight={0: 1, 1: 2})
model_h1n1_weighted.fit(X_train_h1n1, y_train_h1n1)

# Prédictions et évaluation
y_pred_h1n1_weighted = model_h1n1_weighted.predict(X_val_h1n1)
print("Confusion Matrix:\n", confusion_matrix(y_val_h1n1, y_pred_h1n1_weighted))
print("Classification Report:\n", classification_report(y_val_h1n1, y_pred_h1n1_weighted))


C:\Users\loris\Documents\Anaconda\Lib\site-packages\sklearn\experimental\enable_hist_gradient_boosting.py:16: UserWarning: Since version 1.0, it is not needed to import enable_hist_gradient_boosting anymore. HistGradientBoostingClassifier and HistGradientBoostingRegressor are now stable and can be normally imported from sklearn.ensemble.
  warnings.warn(


Confusion Matrix:
 [[3772  440]
 [ 416  714]]
Classification Report:
               precision    recall  f1-score   support

         0.0       0.90      0.90      0.90      4212
         1.0       0.62      0.63      0.63      1130

    accuracy                           0.84      5342
   macro avg       0.76      0.76      0.76      5342
weighted avg       0.84      0.84      0.84      5342



In [44]:
# Étape 3 : Utilisation de Techniques d'Ensemble Spécialisées
from imblearn.ensemble import BalancedRandomForestClassifier  # Importation nécessaire
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Étape 3 : Utilisation de Techniques d'Ensemble Spécialisées
brf = BalancedRandomForestClassifier(n_estimators=100, random_state=42)
brf.fit(X_train_h1n1, y_train_h1n1)
y_pred_brf_h1n1 = brf.predict(X_val_h1n1)

# Évaluer les performances
print("Confusion Matrix:\n", confusion_matrix(y_val_h1n1, y_pred_brf_h1n1))
print("Classification Report:\n", classification_report(y_val_h1n1, y_pred_brf_h1n1))


C:\Users\loris\Documents\Anaconda\Lib\site-packages\imblearn\ensemble\_forest.py:546: FutureWarning: The default of `sampling_strategy` will change from `'auto'` to `'all'` in version 0.13. This change will follow the implementation proposed in the original paper. Set to `'all'` to silence this warning and adopt the future behaviour.
  warn(
C:\Users\loris\Documents\Anaconda\Lib\site-packages\imblearn\ensemble\_forest.py:558: FutureWarning: The default of `replacement` will change from `False` to `True` in version 0.13. This change will follow the implementation proposed in the original paper. Set to `True` to silence this warning and adopt the future behaviour.
  warn(


Confusion Matrix:
 [[3371  841]
 [ 266  864]]
Classification Report:
               precision    recall  f1-score   support

         0.0       0.93      0.80      0.86      4212
         1.0       0.51      0.76      0.61      1130

    accuracy                           0.79      5342
   macro avg       0.72      0.78      0.73      5342
weighted avg       0.84      0.79      0.81      5342



In [43]:
# Étape 4 : Rééchantillonnage Avancé des Données
pipeline_smote_h1n1 = ImbPipeline(steps=[('smote', SMOTE(sampling_strategy='minority', random_state=42)), ('under', RandomUnderSampler(sampling_strategy='majority', random_state=42)), ('model', GradientBoostingClassifier(n_estimators=100, learning_rate=0.1, random_state=42))])
pipeline_smote_h1n1.fit(X_train_h1n1, y_train_h1n1)
y_pred_smote_h1n1 = pipeline_smote_h1n1.predict(X_val_h1n1)
print("Confusion Matrix:\n", confusion_matrix(y_val_h1n1, y_pred_smote_h1n1))
print("Classification Report:\n", classification_report(y_val_h1n1, y_pred_smote_h1n1))

Confusion Matrix:
 [[3947  265]
 [ 534  596]]
Classification Report:
               precision    recall  f1-score   support

         0.0       0.88      0.94      0.91      4212
         1.0       0.69      0.53      0.60      1130

    accuracy                           0.85      5342
   macro avg       0.79      0.73      0.75      5342
weighted avg       0.84      0.85      0.84      5342



In [46]:
# Étape 5 : Optimisation des Hyperparamètres
from sklearn.experimental import enable_hist_gradient_boosting  # Nécessaire pour activer le modèle
from sklearn.ensemble import HistGradientBoostingClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import confusion_matrix, classification_report

# Remplacer GradientBoostingClassifier par HistGradientBoostingClassifier
param_grid = {
    'max_depth': [3, 5, 7],
    'learning_rate': [0.01, 0.1, 0.2],
    'max_iter': [50, 100, 200],
    'class_weight': [{0: 1, 1: w} for w in [1, 2, 5]]
}

grid_search_h1n1 = GridSearchCV(HistGradientBoostingClassifier(random_state=42), param_grid, scoring='recall', cv=5)
grid_search_h1n1.fit(X_train_h1n1, y_train_h1n1)
best_model_h1n1 = grid_search_h1n1.best_estimator_
y_pred_best_h1n1 = best_model_h1n1.predict(X_val_h1n1)

print("Best Hyperparameters for h1n1_vaccine:", grid_search_h1n1.best_params_)
print("Confusion Matrix:\n", confusion_matrix(y_val_h1n1, y_pred_best_h1n1))
print("Classification Report:\n", classification_report(y_val_h1n1, y_pred_best_h1n1))

Best Hyperparameters for h1n1_vaccine: {'class_weight': {0: 1, 1: 5}, 'learning_rate': 0.01, 'max_depth': 7, 'max_iter': 50}
Confusion Matrix:
 [[2688 1524]
 [ 133  997]]
Classification Report:
               precision    recall  f1-score   support

         0.0       0.95      0.64      0.76      4212
         1.0       0.40      0.88      0.55      1130

    accuracy                           0.69      5342
   macro avg       0.67      0.76      0.66      5342
weighted avg       0.83      0.69      0.72      5342

